apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: app
          image: michealng385/demo-k8s:2.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config 
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
          imagePullPolicy: Always
